### ISSUE TITLE
Clang 7 fails with linker error

### ISSUE THREAD

**Issue by offa** [offa/keygen#32]
Clang 7 (#31) fails with linker error:

```
/usr/bin/ld: ArgumentTest: hidden symbol `_ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE11__recommendEm' isn't defined
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by offa** [comment]
Build with UBSan enabled is broken.

**Workaround:** Disable Sanitizer until fixed.

**Comment by arrtchiu** [comment]
I'm building a different project with Clang 7 and ASAN + UBSAN and receiving the exact same linker error. Did you manage to find a fix?

**Comment by offa** [comment]
Unfortunately not. I experience this error on some other projects too – but only with Clang 7 on Ubuntu.

**Comment by offa** [comment]
@arrtchiu Clang 8 is not affected by this problem.

**Comment by offa** [comment]
As Clang 7 on Ubuntu 18 is the only affected configuration, the simplest solution is to upgrade to Clang 8. CI builds can stick with the workaround.
